name: FoxTales CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - dev

env:
  DOTNET_VERSION: 9.0.x
  BUILD_CONFIG: Release

jobs:
  test:
    name: Tests and Linter
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Prepare .NET install path
        run: |
          mkdir -p $HOME/.dotnet
          export DOTNET_ROOT=$GITHUB_WORKSPACE/.dotnet
          export DOTNET_INSTALL_DIR=$GITHUB_WORKSPACE/.dotnet
          export DOTNET_CLI_HOME=$GITHUB_WORKSPACE/.dotnet
          echo "DOTNET_ROOT=$HOME/.dotnet" >> $GITHUB_ENV
          echo "DOTNET_INSTALL_DIR=$HOME/.dotnet" >> $GITHUB_ENV
          echo "$HOME/.dotnet" >> $GITHUB_PATH

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dotnet tools
        run: dotnet tool restore

      - name: Check code formatting
        run: dotnet format HubWorkspace.sln --verify-no-changes --verbosity minimal

      - name: Build and run tests
        run: |
          dotnet restore FoxTales.Tests/FoxTales.Application.Tests/FoxTales.Application.Tests.csproj
          dotnet build FoxTales.Tests/FoxTales.Application.Tests/FoxTales.Application.Tests.csproj --configuration $BUILD_CONFIG --no-restore
          dotnet test FoxTales.Tests/FoxTales.Application.Tests/FoxTales.Application.Tests.csproj \
            --configuration $BUILD_CONFIG \
            --no-build \
            --logger "console;verbosity=detailed"

      - name: Cleanup
        if: always()
        run: |
          rm -rf $HOME/.dotnet
          find $GITHUB_WORKSPACE/FoxTales -type d \( -name bin -o -name obj \) -exec rm -rf {} +